FROM alpine:latest

RUN apk add --no-cache \
    gcc \
    musl-dev \
    make \
    pkgconfig \
    sqlite-dev \
    icu-dev \
    wget \
    unzip \
    file

WORKDIR /output

RUN wget -q https://www.sqlite.org/2024/sqlite-amalgamation-3460000.zip && \
    unzip -q sqlite-amalgamation-3460000.zip && \
    cp sqlite-amalgamation-3460000/sqlite3ext.h . && \
    cp sqlite-amalgamation-3460000/sqlite3.h . && \
    rm -rf sqlite-amalgamation-3460000*

COPY icu.c /output/
COPY build-alpine.sh /output/
RUN chmod +x /output/build-alpine.sh
RUN /output/build-alpine.sh