FROM ubuntu:24.04

RUN apt-get update -q && \
    apt-get install -y \
        gcc \
        make \
        pkg-config \
        libsqlite3-dev \
        libicu-dev \
        sqlite3 \
        wget \
        unzip \
        file && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /output

RUN wget -q https://www.sqlite.org/2024/sqlite-amalgamation-3460000.zip && \
    unzip -q sqlite-amalgamation-3460000.zip && \
    cp sqlite-amalgamation-3460000/sqlite3ext.h . && \
    cp sqlite-amalgamation-3460000/sqlite3.h . && \
    rm -rf sqlite-amalgamation-3460000*

COPY icu.c /output/
COPY build-ubuntu.sh /output/
RUN chmod +x /output/build-ubuntu.sh
RUN /output/build-ubuntu.sh